# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903e5369b1f795c6ddfa7fd873a2d06caacb4e13ec19a1e646a499c4c04c575e15d1db3305c23a7b8497bdd05caa75c09d1ebb2eb011e590e455a5779179f8ec

test:
  secret_key_base: 417b5545a2f48b1f27c4eadeeba6f84b2079434ee3368abc95d06888275e38422050157eb1d8cbc99d59a41e8f302c51887f2ec06a332f186960eb76925e1435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
